#spring.application.name=spring-ai
##---------------Anthropoc------------------------------------
#spring.ai.anthropic.api-key=YOUR_API_KEY
#spring.ai.anthropic.chat.options.model=claude-3-5-sonnet-latest
#spring.ai.anthropic.chat.options.temperature=0.7
#spring.ai.anthropic.chat.options.max-tokens=450
##--------------Azure Open AI------------------------------------
#spring.ai.azure.openai.api-key=YOUR_API_KEY
#spring.ai.azure.openai.endpoint=YOUR_ENDPOINT
#spring.ai.azure.openai.chat.options.deployment-name=gpt-4o
#spring.ai.azure.openai.chat.options.temperature=0.7
##---------------Mistral AI---------------------------------
#spring.ai.mistralai.api-key=YOUR_API_KEY
#spring.ai.mistralai.chat.options.model=mistral-small
#spring.ai.mistralai.chat.options.temperature=0.7
##----------------Ollama------------------------------------
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=mistral
#spring.ai.ollama.chat.options.temperature=0.7
##---------------Open AI Configuration-------------------------
#spring.ai.openai.api-key=YOUR_API_KEY
#spring.ai.openai.chat.options.model=gpt-4o
#spring.ai.openai.chat.options.temperature=0.7
##---------------Vertex AI Gemini-----------------------------
#spring.ai.vertex.ai.gemini.project-id=PROJECT_ID
#spring.ai.vertex.ai.gemini.location=LOCATION
#spring.ai.vertex.ai.gemini.chat.options.model=vertex-pro-vision
#spring.ai.vertex.ai.gemini.chat.options.temperature=0.5